# Generated by Django 6.0.3 on 2026-03-25 14:00

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import tenants.models
import tenants.wagtail_locales
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization or company name.', max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g., 'acme-corp'). Must be unique.", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tenants cannot log in or access data.')),
                ('preferred_language', models.CharField(choices=tenants.wagtail_locales.wagtail_locale_choices, default='en', help_text='Default locale for this tenant (admin strings, API fallbacks). Options match Wagtail Settings → Locales.', max_length=32)),
                ('branding_site_name', models.CharField(blank=True, help_text='Custom site name shown in the admin header. Falls back to tenant name.', max_length=255)),
                ('branding_primary_color', models.CharField(blank=True, help_text="Hex color code for primary brand color (e.g., '#3B82F6').", max_length=7)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of users allowed under the current plan.')),
                ('max_products', models.PositiveIntegerField(default=100, help_text='Maximum number of active products allowed.')),
                ('max_users_override', models.PositiveIntegerField(blank=True, help_text='Platform override: temporarily increase user limit. Leave blank to use plan default.', null=True)),
                ('max_products_override', models.PositiveIntegerField(blank=True, help_text='Platform override: temporarily increase product limit. Leave blank to use plan default.', null=True)),
                ('billing_notes', models.TextField(blank=True, help_text='Optional notes for billing support (e.g., payment issues, custom arrangements).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branding_logo', models.ForeignKey(blank=True, help_text='Custom logo displayed in the admin header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the person being invited.', max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('token', models.CharField(default=tenants.models._make_token, editable=False, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'coordinator', 'manager', 'viewer'])), name='tenants_tenantinvitation_role_allowed')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive memberships are preserved for audit but deny access.')),
                ('is_default', models.BooleanField(default=False, help_text='If True, this tenant is loaded automatically on login.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'tenant__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'coordinator', 'manager', 'viewer'])), name='tenants_tenantmembership_role_allowed')],
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
