# Generated by Django 6.0.3 on 2026-03-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenantmembership_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_products_override',
            field=models.PositiveIntegerField(blank=True, help_text='Platform override: temporarily increase product limit. Leave blank to use plan default.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_users_override',
            field=models.PositiveIntegerField(blank=True, help_text='Platform override: temporarily increase user limit. Leave blank to use plan default.', null=True),
        ),
    ]
