# Generated by Django 6.0.3 on 2026-03-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_tenant_limit_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_notes',
            field=models.TextField(blank=True, help_text='Optional notes for billing support (e.g., payment issues, custom arrangements).'),
        ),
    ]
