# Generated by Django 6.0.3 on 2026-03-17 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_slug_alter_product_sku_and_more'),
        ('sales', '0002_customer_tenant_dispatch_tenant_salesorder_tenant_and_more'),
        ('tenants', '0002_populate_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique customer code per tenant (e.g., CUST-001).', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_number',
            field=models.CharField(db_index=True, help_text='Unique dispatch number per tenant (e.g., DSP-2026-001).', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(db_index=True, help_text='Unique sales order number per tenant (e.g., SO-2026-001).', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_customer_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='dispatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'dispatch_number'), name='unique_dispatch_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='unique_so_number_per_tenant'),
        ),
    ]
