# Generated by Django 6.0.3 on 2026-03-20 18:04

import django.db.models.deletion
from django.db import migrations, models


def _default_tenant(apps):
    Tenant = apps.get_model("tenants", "Tenant")
    tenant, _ = Tenant.objects.get_or_create(
        slug="default",
        defaults={"name": "Default", "is_active": True},
    )
    return tenant


def backfill_sales_tenant(apps, schema_editor):
    """Backfill NULL tenant on sales models before enforcing non-null."""
    Customer = apps.get_model("sales", "Customer")
    SalesOrder = apps.get_model("sales", "SalesOrder")
    Dispatch = apps.get_model("sales", "Dispatch")
    default_pk = _default_tenant(apps).pk

    Customer.objects.filter(tenant__isnull=True).update(tenant_id=default_pk)

    for so in SalesOrder.objects.filter(tenant__isnull=True).select_related("customer"):
        so.tenant_id = (so.customer.tenant_id if so.customer_id else None) or default_pk
        so.save(update_fields=["tenant_id"])

    for d in Dispatch.objects.filter(tenant__isnull=True).select_related("sales_order"):
        d.tenant_id = (d.sales_order.tenant_id if d.sales_order_id else None) or default_pk
        d.save(update_fields=["tenant_id"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_add_tenant_to_salesorderline"),
        ("tenants", "0006_add_billing_notes"),
    ]

    operations = [
        migrations.RunPython(backfill_sales_tenant, reverse_noop),
        migrations.AlterField(
            model_name="customer",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
    ]
