# Generated by Django 6.0.3 on 2026-03-25 14:00

import django.db.models.deletion
import modelsearch.index
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('stock_received', 'Stock Received'), ('stock_issued', 'Stock Issued'), ('stock_transferred', 'Stock Transferred'), ('stock_adjusted', 'Stock Adjusted'), ('reservation_created', 'Reservation Created'), ('reservation_fulfilled', 'Reservation Fulfilled'), ('reservation_cancelled', 'Reservation Cancelled'), ('cycle_count_started', 'Cycle Count Started'), ('cycle_count_reconciled', 'Cycle Count Reconciled'), ('bulk_operation', 'Bulk Operation'), ('tenant_accessed', 'Tenant Accessed'), ('tenant_deactivated', 'Tenant Deactivated'), ('tenant_reactivated', 'Tenant Reactivated'), ('tenant_limit_overridden', 'Tenant Limit Overridden'), ('impersonation_started', 'Impersonation Started'), ('impersonation_ended', 'Impersonation Ended'), ('tenant_export', 'Tenant Data Exported')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Context-specific data: lot numbers, quantities, location names, etc.')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_quantity', models.IntegerField(help_text='System stock at time of count.')),
                ('counted_quantity', models.IntegerField(blank=True, help_text='Physical count entered by warehouse staff.', null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Descriptive name for this cycle count (e.g., 'Q1 2026 Full Count').", max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reconciled', 'Reconciled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Date when the cycle count is planned to take place.')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when counting actually began.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when counting was finished.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variance_type', models.CharField(choices=[('shortage', 'Shortage'), ('surplus', 'Surplus'), ('match', 'Match')], max_length=20)),
                ('system_quantity', models.IntegerField()),
                ('physical_quantity', models.IntegerField()),
                ('variance_quantity', models.IntegerField(help_text='physical_quantity − system_quantity (negative = shortage).')),
                ('resolution', models.CharField(blank=True, choices=[('accepted', 'Accepted (Adjustment Created)'), ('investigating', 'Under Investigation'), ('rejected', 'Rejected (No Change)')], max_length=20, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, help_text='Unique Stock Keeping Unit identifier (e.g., PHONE-001). Unique per tenant.', max_length=100, verbose_name='SKU')),
                ('name', models.CharField(help_text="The product name displayed to users (e.g., 'iPhone 15 Pro').", max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Detailed product description with rich text formatting. Optional.')),
                ('unit_of_measure', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('lt', 'Liters'), ('m', 'Meters'), ('box', 'Boxes'), ('pack', 'Packs')], default='pcs', help_text='The unit used to measure this product (pieces, kilograms, liters, etc.).', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='The default or latest purchase cost per unit. Used for inventory valuation.', max_digits=10)),
                ('reorder_point', models.PositiveIntegerField(default=0, help_text='When stock at any location falls to or below this amount, a low-stock alert is triggered. Set to 0 to disable alerts.')),
                ('tracking_mode', models.CharField(choices=[('none', 'No Tracking'), ('optional', 'Optional Lot Tracking'), ('required', 'Required Lot Tracking')], default='none', help_text='Whether lot/batch tracking is required for this product.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products are hidden from most displays but preserved for historical records.')),
            ],
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text="Optional caption for the image (e.g., 'Front view', 'Product packaging').", max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('auto_reserve_on_order', models.BooleanField(default=False)),
                ('reservation_expiry_hours', models.PositiveIntegerField(default=72)),
                ('allocation_strategy', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO')], default='FIFO', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Location name (e.g., 'Bin A1-1', 'Aisle A', 'Main Warehouse').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this location and its purpose.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive locations are excluded from stock operations but preserved for history.')),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum stock units this location can hold. Null = unlimited.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(db_index=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('received_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['received_date', 'pk'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at the time of this movement.', max_digits=10, null=True)),
                ('movement_type', models.CharField(choices=[('receive', 'Receive'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Optional reference (e.g. PO number, SO number).', max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='StockMovementLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive warehouses are hidden from day-to-day operations.')),
                ('timezone_name', models.CharField(blank=True, help_text='IANA timezone name (e.g. America/Chicago), optional.', max_length=64)),
                ('address', models.TextField(blank=True, help_text='Full mailing or physical site address.')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], db_index=True, default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', help_text='Celery AsyncResult ID when dispatched via broker.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="The display name of this category (e.g., 'Electronics', 'Furniture')", max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly name. Auto-generated from name if left blank.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description to explain what products belong in this category.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden from frontend displays but preserved in the database.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
