# Generated by Django 6.0.3 on 2026-03-17 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_category_tenant_product_tenant_stocklocation_tenant_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('tenants', '0002_populate_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly name. Auto-generated from name if left blank.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Unique Stock Keeping Unit identifier (e.g., PHONE-001). Unique per tenant.', max_length=100, verbose_name='SKU'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_category_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='unique_product_sku_per_tenant'),
        ),
    ]
