# Generated by Django 6.0.3 on 2026-03-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_compliance_audit_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklot',
            options={'ordering': ['received_date', 'pk']},
        ),
    ]
