# Generated by Django 6.0.3 on 2026-03-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_reservation_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Optional: reserve against a specific lot for lot-aware fulfillment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='inventory.stocklot'),
        ),
    ]
