# Generated by Django 6.0.3 on 2026-03-18 10:08

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_stock_lot_to_reservation'),
        ('tenants', '0002_populate_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Descriptive name for this cycle count (e.g., 'Q1 2026 Full Count').", max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reconciled', 'Reconciled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Date when the cycle count is planned to take place.')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when counting actually began.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when counting was finished.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Scope to a specific location. Leave blank for a full warehouse count.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_cycles', to='inventory.stocklocation')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles_started', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
