# Generated by Django 6.0.3 on 2026-03-18 10:12

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_cycle_count_line'),
        ('tenants', '0002_populate_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variance_type', models.CharField(choices=[('shortage', 'Shortage'), ('surplus', 'Surplus'), ('match', 'Match')], max_length=20)),
                ('system_quantity', models.IntegerField()),
                ('physical_quantity', models.IntegerField()),
                ('variance_quantity', models.IntegerField(help_text='physical_quantity - system_quantity (negative = shortage).')),
                ('resolution', models.CharField(blank=True, choices=[('accepted', 'Accepted (Adjustment Created)'), ('investigating', 'Under Investigation'), ('rejected', 'Rejected (No Change)')], max_length=20, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('adjustment_movement', models.ForeignKey(blank=True, help_text="Corrective stock movement created when resolution is 'accepted'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockmovement')),
                ('count_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variance_record', to='inventory.cyclecountline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='inventory.inventorycycle')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variances_resolved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
