# Generated by Django 6.0.3 on 2026-03-24 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_add_translatable_mixin_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
