# Generated by Django 6.0.3 on 2026-03-25 08:38

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


def forwards_stocklocation_warehouse_from_roots(apps, schema_editor):
    """Create a Warehouse per existing MP root and attach the subtree."""
    StockLocation = apps.get_model("inventory", "StockLocation")
    Warehouse = apps.get_model("inventory", "Warehouse")

    for root in StockLocation.objects.filter(depth=1).order_by("path"):
        tenant_id = getattr(root, "tenant_id", None)
        if tenant_id is None:
            continue

        wh = Warehouse.objects.create(
            tenant_id=tenant_id,
            name=root.name,
            description=root.description or "",
            is_active=root.is_active,
            timezone_name="",
            created_by_id=getattr(root, "created_by_id", None),
        )
        Warehouse.objects.filter(pk=wh.pk).update(
            created_at=root.created_at,
            updated_at=root.updated_at,
        )

        StockLocation.objects.filter(
            path__startswith=root.path,
            tenant_id=tenant_id,
        ).update(warehouse_id=wh.pk)


def backwards_clear_warehouse_links(apps, schema_editor):
    StockLocation = apps.get_model("inventory", "StockLocation")
    Warehouse = apps.get_model("inventory", "Warehouse")
    StockLocation.objects.all().update(warehouse_id=None)
    Warehouse.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_align_translation_key_with_wagtail'),
        ('tenants', '0008_alter_tenant_preferred_language_wagtail_locales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive warehouses are hidden from day-to-day operations.')),
                ('timezone_name', models.CharField(blank=True, help_text='IANA timezone name (e.g. America/Chicago), optional.', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Facility for this branch of the tree; leave empty for retail-only trees.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_locations', to='inventory.warehouse'),
        ),
        migrations.RunPython(
            forwards_stocklocation_warehouse_from_roots,
            backwards_clear_warehouse_links,
        ),
    ]
