# Generated by Django 6.0.3 on 2026-03-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_warehouse_and_stocklocation_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, help_text='Full mailing or physical site address.'),
        ),
    ]
