"""
Django settings for the_inventory project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.conf import global_settings

from .env_utils import env_bool, env_int, env_list, env_str

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent
# Repository root (parent of src/); .env, frontend/, etc. live here.
REPO_ROOT = BASE_DIR.parent

# Load environment variables from .env at repository root
_env_file = REPO_ROOT / ".env"
try:
    from dotenv import load_dotenv

    load_dotenv(_env_file)
except ImportError:
    # If python-dotenv is not installed, manually load .env
    if _env_file.exists():
        with open(_env_file) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    os.environ.setdefault(key.strip(), value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    "tenants",
    "inventory",
    "procurement",
    "sales",
    "reports",
    "api",
    "seeders",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    "django_celery_results",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtail_localize",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.postgres",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "api.middleware.JWTAuthMiddleware",
    "tenants.middleware.TenantMiddleware",
    "tenants.middleware.ImpersonationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "the_inventory.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "tenants.context_processors.tenant_branding",
            ],
        },
    },
]

WSGI_APPLICATION = "the_inventory.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = env_str("LANGUAGE_CODE", "en") or "en"

# Django's LocaleMiddleware negotiates from Django's built-in ISO catalog.
# ``home.i18n_sync.refresh_i18n_settings_from_wagtail`` merges in every
# ``wagtailcore.Locale`` row (plus Kinyarwanda) on startup, after migrations,
# and when locales change in Wagtail admin.
_base_langs = list(global_settings.LANGUAGES)
if "rw" not in dict(_base_langs):
    _base_langs.append(("rw", "Kinyarwanda"))
LANGUAGES = tuple(_base_langs)

# Bootstrap only until DB locales load (see ``home.i18n_sync``). Must stay a
# subset of LANGUAGES. Replaced at runtime from Wagtail Locale rows.
WAGTAIL_CONTENT_LANGUAGES = [
    ("en", "English"),
]

LOCALE_PATHS = [
    str(BASE_DIR / "locale"),
]

TIME_ZONE = env_str("TIME_ZONE", "UTC") or "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = env_str("STATIC_URL", "/static/") or "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = env_str("MEDIA_URL", "/media/") or "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Cache
# Defaults to local-memory cache so the app works without Redis.
# Override in production.py / local.py to point at a Redis instance.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "the-inventory-default",
    }
}

STOCK_CACHE_TTL = env_int("STOCK_CACHE_TTL_SECONDS", 60 * 10)
DASHBOARD_CACHE_TTL = env_int("DASHBOARD_CACHE_TTL_SECONDS", 60 * 5)

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = env_int("DATA_UPLOAD_MAX_NUMBER_FIELDS", 10_000)


# Wagtail settings (tunable public strings only; search backends stay in code)

WAGTAIL_I18N_ENABLED = True
# Active content languages: see WAGTAIL_CONTENT_LANGUAGES under Internationalization.

WAGTAIL_SITE_NAME = env_str("WAGTAIL_SITE_NAME", "the_inventory") or "the_inventory"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL for Wagtail admin emails / absolute links (no '/admin', no trailing slash).
# Prefer WAGTAILADMIN_BASE_URL; fall back to PUBLIC_BASE_URL or local dev default.
WAGTAILADMIN_BASE_URL = (
    env_str("WAGTAILADMIN_BASE_URL")
    or env_str("PUBLIC_BASE_URL")
    or "http://127.0.0.1:8000"
)

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']


# Django REST Framework

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.authentication.CookieJWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "api.permissions.IsStaffUser",
    ],
    "DEFAULT_PAGINATION_CLASS": "api.pagination.StandardPagination",
    "PAGE_SIZE": env_int("API_PAGE_SIZE", 25),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


# SimpleJWT

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "TOKEN_OBTAIN_SERIALIZER": "api.serializers.auth.InventoryTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "api.serializers.auth.InventoryTokenRefreshSerializer",
}


# CORS — SPA / separate frontend origin (comma-separated origins, full scheme+host+port)

_DEFAULT_CORS_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
]

if env_bool("CORS_ALLOW_ALL_ORIGINS"):
    # Browsers forbid credentials with wildcard origins; do not combine with
    # CORS_ALLOW_CREDENTIALS=True for real auth flows.
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS: list[str] = []
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", default=_DEFAULT_CORS_ORIGINS)

CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", True)

_CORS_BASE_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-tenant",
]
CORS_ALLOW_HEADERS = list(dict.fromkeys(_CORS_BASE_HEADERS + env_list("CORS_EXTRA_HEADERS")))

# CSRF — required for session auth / unsafe methods from a browser on another origin.
# When CORS_ALLOWED_ORIGINS is used, CSRF_TRUSTED_ORIGINS defaults to the same list.
# If you set CORS_ALLOW_ALL_ORIGINS, you must set CSRF_TRUSTED_ORIGINS explicitly.
_csrf_origins = env_list("CSRF_TRUSTED_ORIGINS")
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = _csrf_origins
elif CORS_ALLOW_ALL_ORIGINS:
    CSRF_TRUSTED_ORIGINS = []
else:
    CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

# Cookie / CSRF flags for cross-site frontends (e.g. SPA on another domain over HTTPS).
SESSION_COOKIE_SAMESITE = env_str("SESSION_COOKIE_SAMESITE", "Lax") or "Lax"
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SAMESITE = env_str("CSRF_COOKIE_SAMESITE", "Lax") or "Lax"
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", False)


# drf-spectacular (OpenAPI)

# Frontend base URL for invite links, password reset, etc.
FRONTEND_URL = env_str("FRONTEND_URL", "http://localhost:3000") or "http://localhost:3000"

# Public tenant registration (hosted vs self-hosted)
# When True: anyone can register a new organization via POST /auth/register/
# When False (default): only superuser/staff can create tenants via admin or createtenant
# Hosters set ENABLE_PUBLIC_TENANT_REGISTRATION=True; self-hosted leave default
ENABLE_PUBLIC_TENANT_REGISTRATION = env_bool("ENABLE_PUBLIC_TENANT_REGISTRATION", False)

# JWT impersonation (POST /auth/impersonate/*): platform superuser support-only. Set False to
# disable token swap while keeping Wagtail session impersonation.
ENABLE_API_IMPERSONATION = env_bool("ENABLE_API_IMPERSONATION", True)

# Tenant access audit trail
AUDIT_TENANT_ACCESS = env_bool("AUDIT_TENANT_ACCESS", True)


SPECTACULAR_SETTINGS = {
    "TITLE": env_str("API_DOC_TITLE", "The Inventory API") or "The Inventory API",
    "DESCRIPTION": env_str(
        "API_DOC_DESCRIPTION",
        "RESTful API for The Inventory — a multi-tenant inventory management platform.",
    )
    or "RESTful API for The Inventory — a multi-tenant inventory management platform.",
    "VERSION": env_str("API_DOC_VERSION", "1.0.0") or "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}


# Celery

CELERY_BROKER_URL = (
    env_str("CELERY_BROKER_URL") or env_str("REDIS_URL") or "redis://localhost:6379/0"
)
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ALWAYS_EAGER = env_bool("CELERY_TASK_ALWAYS_EAGER", False)
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER

# Email — only set attributes that are configured (dev.py may force console backend).
_email_backend = env_str("EMAIL_BACKEND")
if _email_backend:
    EMAIL_BACKEND = _email_backend
if env_str("EMAIL_HOST"):
    EMAIL_HOST = env_str("EMAIL_HOST")
    EMAIL_PORT = env_int("EMAIL_PORT", 587)
    EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
    EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
    _user = env_str("EMAIL_HOST_USER")
    if _user:
        EMAIL_HOST_USER = _user
    _pw = env_str("EMAIL_HOST_PASSWORD")
    if _pw:
        EMAIL_HOST_PASSWORD = _pw
_default_from = env_str("DEFAULT_FROM_EMAIL")
if _default_from:
    DEFAULT_FROM_EMAIL = _default_from
