"""Compliance audit action identifiers stored on :class:`~inventory.models.audit.ComplianceAuditLog`."""

from django.db import models


class AuditAction(models.TextChoices):
    STOCK_RECEIVED = "stock_received", "Stock Received"
    STOCK_ISSUED = "stock_issued", "Stock Issued"
    STOCK_TRANSFERRED = "stock_transferred", "Stock Transferred"
    STOCK_ADJUSTED = "stock_adjusted", "Stock Adjusted"
    RESERVATION_CREATED = "reservation_created", "Reservation Created"
    RESERVATION_FULFILLED = "reservation_fulfilled", "Reservation Fulfilled"
    RESERVATION_CANCELLED = "reservation_cancelled", "Reservation Cancelled"
    CYCLE_COUNT_STARTED = "cycle_count_started", "Cycle Count Started"
    CYCLE_COUNT_RECONCILED = "cycle_count_reconciled", "Cycle Count Reconciled"
    BULK_OPERATION = "bulk_operation", "Bulk Operation"

    PRODUCT_CREATED = "product_created", "Product Created"
    PRODUCT_UPDATED = "product_updated", "Product Updated"
    PRODUCT_DELETED = "product_deleted", "Product Deleted"
    CATEGORY_CREATED = "category_created", "Category Created"
    CATEGORY_UPDATED = "category_updated", "Category Updated"
    CATEGORY_DELETED = "category_deleted", "Category Deleted"
    WAREHOUSE_CREATED = "warehouse_created", "Warehouse Created"
    WAREHOUSE_UPDATED = "warehouse_updated", "Warehouse Updated"
    WAREHOUSE_DELETED = "warehouse_deleted", "Warehouse Deleted"
    LOCATION_CREATED = "location_created", "Stock Location Created"
    LOCATION_UPDATED = "location_updated", "Stock Location Updated"
    LOCATION_DELETED = "location_deleted", "Stock Location Deleted"

    CUSTOMER_CREATED = "customer_created", "Customer Created"
    CUSTOMER_UPDATED = "customer_updated", "Customer Updated"
    CUSTOMER_DELETED = "customer_deleted", "Customer Deleted"
    SUPPLIER_CREATED = "supplier_created", "Supplier Created"
    SUPPLIER_UPDATED = "supplier_updated", "Supplier Updated"
    SUPPLIER_DELETED = "supplier_deleted", "Supplier Deleted"

    SALES_ORDER_CREATED = "sales_order_created", "Sales Order Created"
    SALES_ORDER_UPDATED = "sales_order_updated", "Sales Order Updated"
    SALES_ORDER_DELETED = "sales_order_deleted", "Sales Order Deleted"
    SALES_ORDER_CONFIRMED = "sales_order_confirmed", "Sales Order Confirmed"
    SALES_ORDER_CANCELLED = "sales_order_cancelled", "Sales Order Cancelled"
    DISPATCH_CREATED = "dispatch_created", "Dispatch Created"
    DISPATCH_UPDATED = "dispatch_updated", "Dispatch Updated"
    DISPATCH_DELETED = "dispatch_deleted", "Dispatch Deleted"
    DISPATCH_PROCESSED = "dispatch_processed", "Dispatch Processed"

    PURCHASE_ORDER_CREATED = "purchase_order_created", "Purchase Order Created"
    PURCHASE_ORDER_UPDATED = "purchase_order_updated", "Purchase Order Updated"
    PURCHASE_ORDER_DELETED = "purchase_order_deleted", "Purchase Order Deleted"
    PURCHASE_ORDER_CONFIRMED = "purchase_order_confirmed", "Purchase Order Confirmed"
    PURCHASE_ORDER_CANCELLED = "purchase_order_cancelled", "Purchase Order Cancelled"
    GRN_CREATED = "grn_created", "Goods Received Note Created"
    GRN_UPDATED = "grn_updated", "Goods Received Note Updated"
    GRN_DELETED = "grn_deleted", "Goods Received Note Deleted"
    GRN_RECEIVED = "grn_received", "Goods Received Note Processed"

    TENANT_ACCESSED = "tenant_accessed", "Tenant Accessed"
    TENANT_DEACTIVATED = "tenant_deactivated", "Tenant Deactivated"
    TENANT_REACTIVATED = "tenant_reactivated", "Tenant Reactivated"
    TENANT_LIMIT_OVERRIDDEN = "tenant_limit_overridden", "Tenant Limit Overridden"
    IMPERSONATION_STARTED = "impersonation_started", "Impersonation Started"
    IMPERSONATION_ENDED = "impersonation_ended", "Impersonation Ended"
    TENANT_EXPORT = "tenant_export", "Tenant Data Exported"
