# Generated by Django 6.0.3 on 2026-03-17 12:50

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization or company name.', max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g., 'acme-corp'). Must be unique.", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tenants cannot log in or access data.')),
                ('branding_site_name', models.CharField(blank=True, help_text='Custom site name shown in the admin header. Falls back to tenant name.', max_length=255)),
                ('branding_primary_color', models.CharField(blank=True, help_text="Hex color code for primary brand color (e.g., '#3B82F6').", max_length=7)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of users allowed under the current plan.')),
                ('max_products', models.PositiveIntegerField(default=100, help_text='Maximum number of active products allowed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branding_logo', models.ForeignKey(blank=True, help_text='Custom logo displayed in the admin header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive memberships are preserved for audit but deny access.')),
                ('is_default', models.BooleanField(default=False, help_text='If True, this tenant is loaded automatically on login.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'tenant__name'],
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
