# Generated by Django 6.0.3 on 2026-03-19 10:28

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='tenant',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant'),
        ),
    ]
