# Generated by Django 6.0.3 on 2026-03-24 08:56

import tenants.wagtail_locales
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_add_tenant_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='preferred_language',
            field=models.CharField(choices=tenants.wagtail_locales.wagtail_locale_choices, default='en', help_text='Default locale for this tenant (admin strings, API fallbacks). Options match Wagtail Settings → Locales.', max_length=32),
        ),
    ]
