# Generated by Django 6.0.3 on 2026-03-16 12:25

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockmovement_stockrecord'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description to explain what products belong in this category.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive categories are hidden from frontend displays but preserved in the database.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text="The display name of this category (e.g., 'Electronics', 'Furniture')", max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly name. Auto-generated from name if left blank.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select the category this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Detailed product description with rich text formatting. Optional.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive products are hidden from most displays but preserved for historical records.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text="The product name displayed to users (e.g., 'iPhone 15 Pro').", max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(default=0, help_text='When stock at any location falls to or below this amount, a low-stock alert is triggered. Set to 0 to disable alerts.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Unique Stock Keeping Unit identifier (e.g., PHONE-001). Must be unique across all products.', max_length=100, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text="Add tags to help organize and filter products (e.g., 'featured', 'clearance').", through='inventory.ProductTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The default or latest purchase cost per unit. Used for inventory valuation.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('lt', 'Liters'), ('m', 'Meters'), ('box', 'Boxes'), ('pack', 'Packs')], default='pcs', help_text='The unit used to measure this product (pieces, kilograms, liters, etc.).', max_length=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, help_text="Optional caption for the image (e.g., 'Front view', 'Product packaging').", max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(help_text='Upload an image to display for this product.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of this location and its purpose.'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive locations are excluded from stock operations but preserved for history.'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(help_text="Location name (e.g., 'Bin A1-1', 'Aisle A', 'Main Warehouse').", max_length=255),
        ),
    ]
