# Generated by Django 6.0.3 on 2026-03-18 09:30

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_slug_alter_product_sku_and_more'),
        ('procurement', '0003_alter_goodsreceivednote_grn_number_and_more'),
        ('tenants', '0002_populate_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(db_index=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('received_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.product')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='procurement.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='procurement.supplier')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='StockMovementLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_allocations', to='inventory.stocklot')),
                ('stock_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='inventory.stockmovement')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('stock_received', 'Stock Received'), ('stock_issued', 'Stock Issued'), ('stock_transferred', 'Stock Transferred'), ('stock_adjusted', 'Stock Adjusted'), ('reservation_created', 'Reservation Created'), ('reservation_fulfilled', 'Reservation Fulfilled'), ('reservation_cancelled', 'Reservation Cancelled'), ('cycle_count_started', 'Cycle Count Started'), ('cycle_count_reconciled', 'Cycle Count Reconciled'), ('bulk_operation', 'Bulk Operation'), ('tenant_accessed', 'Tenant Accessed')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Context-specific data: lot numbers, quantities, location names, etc.')),
                ('product', models.ForeignKey(blank=True, help_text='Associated product, if applicable to this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'action', 'timestamp'], name='inventory_c_tenant__7e64aa_idx'), models.Index(fields=['tenant', 'timestamp'], name='inventory_c_tenant__c0700a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'lot_number'), name='unique_lot_per_product_per_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='stockmovementlot',
            unique_together={('stock_movement', 'stock_lot')},
        ),
    ]
