# Generated by Django 6.0.3 on 2026-03-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventoryvariance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum stock units this location can hold. Null = unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryvariance',
            name='adjustment_movement',
            field=models.ForeignKey(blank=True, help_text="Corrective stock movement created when resolution is 'accepted'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_variances', to='inventory.stockmovement'),
        ),
        migrations.AlterField(
            model_name='inventoryvariance',
            name='variance_quantity',
            field=models.IntegerField(help_text='physical_quantity − system_quantity (negative = shortage).'),
        ),
    ]
