# Generated by Django 6.0.3 on 2026-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_async_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceauditlog',
            name='action',
            field=models.CharField(choices=[('stock_received', 'Stock Received'), ('stock_issued', 'Stock Issued'), ('stock_transferred', 'Stock Transferred'), ('stock_adjusted', 'Stock Adjusted'), ('reservation_created', 'Reservation Created'), ('reservation_fulfilled', 'Reservation Fulfilled'), ('reservation_cancelled', 'Reservation Cancelled'), ('cycle_count_started', 'Cycle Count Started'), ('cycle_count_reconciled', 'Cycle Count Reconciled'), ('bulk_operation', 'Bulk Operation'), ('tenant_accessed', 'Tenant Accessed'), ('tenant_deactivated', 'Tenant Deactivated'), ('tenant_reactivated', 'Tenant Reactivated'), ('tenant_limit_overridden', 'Tenant Limit Overridden'), ('impersonation_started', 'Impersonation Started'), ('impersonation_ended', 'Impersonation Ended'), ('tenant_export', 'Tenant Data Exported')], max_length=30),
        ),
    ]
