# Generated by Django 6.0.3 on 2026-03-20 18:04

import django.db.models.deletion
from django.db import migrations, models


def _default_tenant(apps):
    Tenant = apps.get_model("tenants", "Tenant")
    tenant, _ = Tenant.objects.get_or_create(
        slug="default",
        defaults={"name": "Default", "is_active": True},
    )
    return tenant


def backfill_cycle_models_tenant(apps, schema_editor):
    """Set tenant from parent cycle before enforcing non-null (matches 0021 pattern)."""
    CycleCountLine = apps.get_model("inventory", "CycleCountLine")
    InventoryVariance = apps.get_model("inventory", "InventoryVariance")
    default_tenant = _default_tenant(apps)
    default_pk = default_tenant.pk

    for line in CycleCountLine.objects.filter(tenant__isnull=True).select_related("cycle"):
        line.tenant_id = line.cycle.tenant_id or default_pk
        line.save(update_fields=["tenant_id"])

    for row in InventoryVariance.objects.filter(tenant__isnull=True).select_related("cycle"):
        row.tenant_id = row.cycle.tenant_id or default_pk
        row.save(update_fields=["tenant_id"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_backfill_and_enforce_tenant"),
        ("tenants", "0006_add_billing_notes"),
    ]

    operations = [
        migrations.RunPython(backfill_cycle_models_tenant, reverse_noop),
        migrations.AlterField(
            model_name="cyclecountline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryvariance",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
    ]
