# Generated by Django 6.0.3 on 2026-03-25 14:00

import django.db.models.deletion
import modelsearch.index
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, help_text='Unique purchase order number per tenant (e.g., PO-2026-001).', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_date', models.DateField(help_text='The date this order was placed.')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected date of goods arrival.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this purchase order.')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units to order.')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit for this line.', max_digits=10)),
            ],
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Unique supplier code per tenant (e.g., SUP-001).', max_length=100)),
                ('name', models.CharField(help_text='Supplier or company name.', max_length=255)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact person at this supplier.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Full mailing or physical address.')),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='Typical delivery lead time in days.')),
                ('payment_terms', models.CharField(choices=[('net_30', 'Net 30'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid')], default='net_30', help_text='Standard payment terms for this supplier.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive suppliers are excluded from new orders but preserved for history.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this supplier.')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grn_number', models.CharField(db_index=True, help_text='Unique GRN number per tenant (e.g., GRN-2026-001).', max_length=100)),
                ('received_date', models.DateField(help_text='The date goods were received.')),
                ('notes', models.TextField(blank=True, help_text='Notes about the goods received (e.g., condition, discrepancies).')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether stock movements have been created for this GRN.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='The location where goods were received into.', on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='inventory.stocklocation')),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
