# Generated by Django 6.0.3 on 2026-03-17 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_slug_alter_product_sku_and_more'),
        ('procurement', '0002_goodsreceivednote_tenant_purchaseorder_tenant_and_more'),
        ('tenants', '0002_populate_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='grn_number',
            field=models.CharField(db_index=True, help_text='Unique GRN number per tenant (e.g., GRN-2026-001).', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(db_index=True, help_text='Unique purchase order number per tenant (e.g., PO-2026-001).', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique supplier code per tenant (e.g., SUP-001).', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='goodsreceivednote',
            constraint=models.UniqueConstraint(fields=('tenant', 'grn_number'), name='unique_grn_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='unique_po_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_supplier_code_per_tenant'),
        ),
    ]
