# Generated by Django 6.0.3 on 2026-03-17 12:18

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_alter_category_description_alter_category_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Unique customer code (e.g., CUST-001).', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Customer or company name.', max_length=255)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact person.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Full mailing or physical address.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive customers are excluded from new orders but preserved for history.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this customer.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, help_text='Unique sales order number (e.g., SO-2026-001).', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_date', models.DateField(help_text='The date this order was placed.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this sales order.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='The customer this order belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.customer')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_number', models.CharField(db_index=True, help_text='Unique dispatch/shipment number (e.g., DSP-2026-001).', max_length=100, unique=True)),
                ('dispatch_date', models.DateField(help_text='The date goods were dispatched.')),
                ('notes', models.TextField(blank=True, help_text='Notes about this dispatch (e.g., tracking number, carrier).')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether stock movements have been created for this dispatch.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(help_text='The location goods are shipped from.', on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='inventory.stocklocation')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='sales.salesorder')),
            ],
            options={
                'verbose_name_plural': 'dispatches',
                'ordering': ['-dispatch_date', '-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units ordered.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit.', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='inventory.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
            ],
            options={
                'unique_together': {('sales_order', 'product')},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
